format = "$username$env_var$all"

[directory]
truncate_to_repo = false
truncation_symbol = "…/"
format = " in [$path]($style)[$read_only]($read_only_style) "

[username]
style_user = "bold blue"
show_always = true
format = "[$user]($style) "

[env_var.SHELL_ICON]
symbol = "$env_value"
style = "bold yellow"

[package]
disabled = true
