format = "$username$os$all"

[username]
style_user = "bold blue"
show_always = true
format = "[$user]($style) "

[os]
format = "with [$symbol]($style)"
style = "bold bright-black"
disabled = false

[os.symbols]
Macos = ""
NixOS = "󱄅"
Ubuntu = ""
Windows = ""

[directory]
truncate_to_repo = false
truncation_symbol = "…/"
format = " in [$path]($style)[$read_only]($read_only_style) "

[aws]
format = 'on [$symbol$profile]($style) '
symbol = ' '
